### ISSUE TITLE
Missing `hash` methods

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#2222]
There are a bunch of our types which implement `==` but not `hash`, which leads to confusing behavior and bugs. E.g. for a vector consisting of two such objects which are equal but not identical, the function `unique` will return a vector with both objects, instead of just one. @YueRen just re-discovered this for `Polyhedron`, but there are more affected types.

We have a small script (taken from https://github.com/oscar-system/Oscar.jl/issues/2222#issuecomment-2578162578 by @lgoettgens) that finds affected types (not perfect, but finds many cases):
```julia
typelist = [];

for package in [Oscar, Hecke, Nemo, AbstractAlgebra]
  Oscar.walkmodules(package) do mod
    append!(typelist, filter(!isnothing, map(methods(==, mod)) do meth
      meth.nargs == 3 || return nothing
      sig = Base.unwrap_unionall(meth.sig)
      arg1_type = sig.types[2]
      arg2_type = sig.types[3]
      arg1_type == arg2_type || return nothing                  # arg1 and arg2 must have the same type to be considered atm
      T = arg1_type
      meth.module == Base && return nothing                     # remove everything without custom ==
      parentmodule(hash, (T, UInt)) == Base || return nothing   # remove everything with custom hash
      T
    end))
  end;
end;

list = map(typelist) do T
  loc = functionloc(==, (T, T))
  if occursin("Oscar.jl/", loc[1])
    loc_cleaned = loc[1][first(findlast("Oscar.jl/", loc[1])):end]
  elseif occursin("packages/", loc[1])
    loc_cleaned = loc[1][(first(findlast("packages/", loc[1])) + length("packages/")):end]
  elseif occursin("julia/base/", loc[1])
    loc_cleaned = loc[1][first(findlast("julia/base/", loc[1])):end]
  else
    loc_cleaned = loc[1]
  end
  T, (T isa TypeVar ? parentmodule(T.ub) : parentmodule(T)), (loc_cleaned, loc[2])
end;

show(IOContext(stdout, :limit => false), "text/plain", list)
```

current list (as of 50eb9d8ef43c5b57ba9eff54686dad6e6d615cb2):
```julia
11-element Vector{Tuple{Type, Module, Tuple{String, Int32}}}:
 (Oscar.PartialCharacter{T<:FieldElem}, Oscar, ("Oscar.jl/src/Rings/binomial_ideals.jl", 408))
 (Oscar.OrderedMultiIndex{T}, Oscar, ("Oscar.jl/src/Combinatorics/OrderedMultiIndex.jl", 93))
 (SubquoModule{T<:AbsLocalizedRingElem}, Oscar, ("Oscar.jl/src/Modules/missing_functionality.jl", 76))
 (SubquoModule{T}, Oscar, ("Oscar.jl/src/Modules/UngradedModules/SubquoModule.jl", 1051))
 (Oscar.GaloisGrp.BoundRingElem, Oscar.GaloisGrp, ("Oscar.jl/src/NumberTheory/GaloisGrp/GaloisGrp.jl", 67))
 (Oscar.GrpCoh.CoChain{N, G, M}, Oscar.GrpCoh, ("Oscar.jl/experimental/GModule/src/Cohomology.jl", 648))
 (Oscar.GrpExt_module.GrpExtElem, Oscar.GrpExt_module, ("Oscar.jl/experimental/GModule/src/GrpExt.jl", 259))
 (Oscar.SubfieldLattice_Module.SubfieldLatticeElem, Oscar.SubfieldLattice_Module, ("Oscar.jl/experimental/GaloisGrp/src/Subfields.jl", 98))
 (AbstractAlgebra.FPModule{T<:RingElement}, AbstractAlgebra, ("AbstractAlgebra/eTkfW/src/Module.jl", 198))
 (AbstractAlgebra.Generic.QuotientModule{T<:RingElement}, AbstractAlgebra.Generic, ("AbstractAlgebra/eTkfW/src/generic/QuotientModule.jl", 101))
 (AbstractAlgebra.Generic.SymmetricGroup, AbstractAlgebra.Generic, ("AbstractAlgebra/eTkfW/src/generic/PermGroups.jl", 406))
```

**Comment by lgoettgens** [comment]
I wrote some small script (NEEDS julia 1.11.1!!!!) to get all cases, including the package that defines the type, and the file and line number the `==` method is defined (in some nice printing):
```julia
list = map(
  filter(names(Oscar; all=true)) do name
    isdefined(Oscar, name) || return false            # remove all wrong exports (see #1964)
    T = getfield(Oscar, name)
    T isa DataType || T isa UnionAll || return false  # remove all non-types and non-parametric-types
    parentmodule(==, (T, T)) == Base && return false  # remove everything without custom ==
    loc = functionloc(==, (T, T))
    endswith(loc[1], "julia/base/Base.jl") && loc[2] == 207 && return false  # remove everything without custom ==
    T <: AbstractArray && endswith(loc[1], "julia/base/abstractarray.jl") && loc[2] == 3028 && return false  # remove AbstractArray subtypes as Base provides both == and hash for them
    parentmodule(hash, (T, UInt)) == Base             # keep iff there is no custom hash
  end,
) do name
  T = getfield(Oscar, name)
  loc = functionloc(==, (T, T))
  if occursin("Oscar.jl/", loc[1])
    loc_cleaned = loc[1][first(findlast("Oscar.jl/", loc[1])):end]
  elseif occursin("packages/", loc[1])
    loc_cleaned = loc[1][(first(findlast("packages/", loc[1])) + length("packages/")):end]
  elseif occursin("julia/base/", loc[1])
    loc_cleaned = loc[1][first(findlast("julia/base/", loc[1])):end]
  else
    loc_cleaned = loc[1]
  end
  name, parentmodule(T), (loc_cleaned, loc[2])
end;
```

Currently (on cd79a0b), I get the following list of things:
```julia
julia> show(IOContext(stdout, :limit => false), "text/plain", list)
6-element Vector{Tuple{Symbol, Module, Tuple{String, Int32}}}:
 (:ClassField, Hecke, ("Hecke/3LoSB/src/RCF/class_fields.jl", 240))
 (:FinGenAbGroupHom, Hecke, ("Hecke/3LoSB/src/GrpAb/Map.jl", 217))
 (:FractionalIdeal, Oscar, ("Oscar.jl/src/Rings/FractionalIdeal.jl", 55))
 (:GenOrdFracIdl, Hecke, ("Hecke/3LoSB/src/GenOrd/FractionalIdeal.jl", 272))
 (:OrdLocElem, Hecke, ("AbstractAlgebra/lVsyJ/src/NCRings.jl", 86))
 (:SLPoly, Oscar, ("AbstractAlgebra/lVsyJ/src/NCRings.jl", 86))
```

One needs unfortunately to check the `==` methods by hand. If they are just delegating to `objectid(-) == objected(-)`, I would propose to remove them, to make disappear from this list.

**Comment by fingolfin** [comment]
@lgoettgens can you please refresh that list? and then we can whittle it down and mark known false-positives.

**Comment by fieker** [comment]
The main offender is ... the Geometry ... @HechtiDerLachs will look into the Geometry...
everyone else, when bored with life, will tackle random other types.
and the script needs improvements - any one with ideas step forward.

**Comment by HechtiDerLachs** [comment]
> @HechtiDerLachs will look into the Geometry 

Done, see #4305 .

**Comment by lgoettgens** [comment]
I updated the list above.

@HechtiDerLachs It seems you missed some types in `AlgebraicGeometry/Schemes/Sheaves/IdealSheaves.jl` (see the list above for the concrete types)

**Comment by lgoettgens** [comment]
With https://github.com/oscar-system/Oscar.jl/pull/4366 and https://github.com/oscar-system/Oscar.jl/pull/4369 all (or maybe I missed some very few) offenders in Oscar should be addressed. I'll update the list once they are merged.

**Comment by alexej-jordan** [comment]
#4354 has just been merged, too

**Comment by lgoettgens** [comment]
> Currently (on [cd79a0b](https://github.com/oscar-system/Oscar.jl/commit/cd79a0bc869770d479277d4e3b2a996f21e9392e)), I get the following list of things:
> 
> ```julia
> julia> show(IOContext(stdout, :limit => false), "text/plain", list)
> 6-element Vector{Tuple{Symbol, Module, Tuple{String, Int32}}}:
>  (:ClassField, Hecke, ("Hecke/3LoSB/src/RCF/class_fields.jl", 240))
>  (:FinGenAbGroupHom, Hecke, ("Hecke/3LoSB/src/GrpAb/Map.jl", 217))
>  (:FractionalIdeal, Oscar, ("Oscar.jl/src/Rings/FractionalIdeal.jl", 55))
>  (:GenOrdFracIdl, Hecke, ("Hecke/3LoSB/src/GenOrd/FractionalIdeal.jl", 272))
>  (:OrdLocElem, Hecke, ("AbstractAlgebra/lVsyJ/src/NCRings.jl", 86))
>  (:SLPoly, Oscar, ("AbstractAlgebra/lVsyJ/src/NCRings.jl", 86))
> ```

After new releases of Hecke and AA are now available here, the list is now drastically shorter.

**Comment by lgoettgens** [comment]
@thofma will have a look at the remaining few Hecke ones.

`FractionalIdeal` will just need a dummy hash function. (see https://github.com/oscar-system/Oscar.jl/pull/4428)

`SLPoly` can get some proper hash function, but this will need a few more hash functions for all types that occur inside of it.

**Comment by thofma** [comment]
https://github.com/thofma/Hecke.jl/pull/1719

**Comment by lgoettgens** [comment]
I have an updated script for finding more offending cases. The previous iteration missed all non-exported types in submodules (e.g. `Oscar.StraightLinePrograms.SLProgram`), and all equality functions with type parameters (i.e. `==(ParametricType{T}, ParametricType{T}) where T`). The following script should find all of these as well, in all of Oscar, Hecke, Nemo, AA, and their submodules.

script:
```julia
typelist = [];

for package in [Oscar, Hecke, Nemo, AbstractAlgebra]
  Oscar.walkmodules(package) do mod
    append!(typelist, filter(!isnothing, map(methods(==, mod)) do meth
      meth.nargs == 3 || return nothing
      sig = Base.unwrap_unionall(meth.sig)
      arg1_type = sig.types[2]
      arg2_type = sig.types[3]
      arg1_type == arg2_type || return nothing                  # arg1 and arg2 must have the same type to be considered atm
      T = arg1_type
      meth.module == Base && return nothing                     # remove everything without custom ==
      parentmodule(hash, (T, UInt)) == Base || return nothing   # remove everything with custom hash
      T
    end))
  end;
end;

list = map(typelist) do T
  loc = functionloc(==, (T, T))
  if occursin("Oscar.jl/", loc[1])
    loc_cleaned = loc[1][first(findlast("Oscar.jl/", loc[1])):end]
  elseif occursin("packages/", loc[1])
    loc_cleaned = loc[1][(first(findlast("packages/", loc[1])) + length("packages/")):end]
  elseif occursin("julia/base/", loc[1])
    loc_cleaned = loc[1][first(findlast("julia/base/", loc[1])):end]
  else
    loc_cleaned = loc[1]
  end
  T, (T isa TypeVar ? parentmodule(T.ub) : parentmodule(T)), (loc_cleaned, loc[2])
end;

show(IOContext(stdout, :limit => false), "text/plain", list)
```

current list (as of 9627744):
```julia
30-element Vector{Tuple{Any, Module, Tuple{String, Int32}}}:
 (SubquoModule{T<:AbsLocalizedRingElem}, Oscar, ("Oscar.jl/src/Modules/missing_functionality.jl", 76))
 (SubquoModule{T}, Oscar, ("Oscar.jl/src/Modules/UngradedModules/SubquoModule.jl", 1051))
 (Oscar.OrderedMultiIndex{T}, Oscar, ("Oscar.jl/src/Combinatorics/OrderedMultiIndex.jl", 93))
 (Oscar.PartialCharacter{T<:FieldElem}, Oscar, ("Oscar.jl/src/Rings/binomial_ideals.jl", 408))
 (Oscar.GaloisGrp.BoundRingElem, Oscar.GaloisGrp, ("Oscar.jl/src/NumberTheory/GaloisGrp/GaloisGrp.jl", 69))
 (Oscar.GrpCoh.CoChain{N, G, M}, Oscar.GrpCoh, ("Oscar.jl/experimental/GModule/src/Cohomology.jl", 642))
 (Oscar.GrpExt_module.GrpExtElem, Oscar.GrpExt_module, ("Oscar.jl/experimental/GModule/src/GrpExt.jl", 78))
 (Oscar.SubfieldLattice_Module.SubfieldLatticeElem, Oscar.SubfieldLattice_Module, ("Oscar.jl/experimental/GaloisGrp/src/Subfields.jl", 98))
 (Hecke.CMType, Hecke, ("Hecke/9Lj2E/src/NumField/CM.jl", 60))
 (Hecke.MapParent, Hecke, ("Hecke/9Lj2E/src/GrpAb/Map.jl", 508))
 (Hecke.AlgAssAbsOrdIdlSet, Hecke, ("Hecke/9Lj2E/src/AlgAssAbsOrd/Ideal.jl", 1492))
 (Hecke.RelNumFieldOrder, Hecke, ("Hecke/9Lj2E/src/NumFieldOrd/NfRelOrd/NfRelOrd.jl", 616))
 (Hecke.LocalQuadSpaceCls, Hecke, ("Hecke/9Lj2E/src/QuadForm/Quad/Spaces.jl", 2144))
 (Hecke.AlgAssAbsOrd, Hecke, ("Hecke/9Lj2E/src/AlgAssAbsOrd/Order.jl", 543))
 (Hecke.RelFinFieldElem{S, T}, Hecke, ("Hecke/9Lj2E/src/Misc/RelFiniteField.jl", 144))
 (HypellCrvPt{T}, Hecke, ("Hecke/9Lj2E/src/HypellCrv/HypellCrv.jl", 490))
 (Hecke.ModAlgAssElem{P, T}, Hecke, ("Hecke/9Lj2E/src/ModAlgAss/ModAlgAss.jl", 120))
 (Hecke.AlgAssRelOrdIdl{S, T, U}, Hecke, ("Hecke/9Lj2E/src/AlgAssRelOrd/Ideal.jl", 729))
 (Hecke.AbsAlgAssIdl, Hecke, ("Hecke/9Lj2E/src/AlgAss/Ideal.jl", 294))
 (HypellCrv{T}, Hecke, ("Hecke/9Lj2E/src/HypellCrv/HypellCrv.jl", 218))
 (Hecke.AbsNumFieldOrderIdealSet, Hecke, ("Hecke/9Lj2E/src/NumFieldOrd/NfOrd/Ideal/Ideal.jl", 69))
 (Hecke.AlgAssRelOrd, Hecke, ("Hecke/9Lj2E/src/AlgAssRelOrd/Order.jl", 371))
 (Hecke.QuadSpaceCls, Hecke, ("Hecke/9Lj2E/src/QuadForm/Quad/Spaces.jl", 2340))
 (Hecke.AbsNumFieldOrderFractionalIdealSet, Hecke, ("Hecke/9Lj2E/src/NumFieldOrd/NfOrd/FracIdeal.jl", 169))
 (Hecke.RCFCharacter, Hecke, ("Hecke/9Lj2E/src/RCF/rcf_stark.jl", 23))
 (T<:Hecke.ModAlgAssLat, Hecke, ("Hecke/9Lj2E/src/ModAlgAss/Lattices/Basics.jl", 192))
 (Hecke.IE.FactoredIdeal, Hecke.IE, ("Hecke/9Lj2E/src/NumFieldOrd/NfOrd/Ideal/Enum.jl", 20))
 (AbstractAlgebra.FPModule{T<:RingElement}, AbstractAlgebra, ("AbstractAlgebra/xy6Re/src/Module.jl", 198))
 (AbstractAlgebra.Generic.SymmetricGroup, AbstractAlgebra.Generic, ("AbstractAlgebra/xy6Re/src/generic/PermGroups.jl", 406))
 (AbstractAlgebra.Generic.QuotientModule{T<:RingElement}, AbstractAlgebra.Generic, ("AbstractAlgebra/xy6Re/src/generic/QuotientModule.jl", 101))
```

**Comment by fingolfin** [comment]
@lgoettgens what would you like triage to discuss about this? 

In the end we need to assign people to work on each... @fieker and me will think about this

**Comment by lgoettgens** [comment]
> @lgoettgens what would you like triage to discuss about this?

we discussed this is triage a few weeks ago and found people that wanted to take care of the few remaining cases (cf. https://github.com/oscar-system/Oscar.jl/issues/2222#issuecomment-2577386030). However, I later improved the script that generates the cases, and so there are now about 30 types missing a hash function. I tagged triage in the hopes that people with domain knowledge to one of the types would volunteer to take care of that one.

**Comment by fingolfin** [comment]
Another thing @jamesnohilly and @emikelsons maybe could have a look (of course together with some of us for initial guidance)

**Comment by thofma** [comment]
I hopefully addressed the hash methods for types coming from Hecke (will be available in 0.35.11).

**Comment by lgoettgens** [comment]
> I hopefully addressed the hash methods for types coming from Hecke (will be available in 0.35.11).

After updating the list (now in the topmost comment), there are only 11 cases left
