### ISSUE TITLE
Orbits of permutation groups on integers should be faster

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3287]
@ThomasBreuer and me discussed this before but I think there is no issue for it, so I am making one now.

Certain orbit computations in OSCAR are much slower than in GAP, for various reasons, some known, some probably still unknown.

But here is the problem in the form of a code example. Compare:
```
julia> G = symmetric_group(5)
Sym(5)

julia> @benchmark collect(orbit(G, 1))
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  15.666 μs … 168.625 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     16.167 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   16.268 μs ±   1.641 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

          ▃ ▃▆█▇ ▃▅▅▂
  ▂▂▂▃▁▄▆██▁████▆████▇▄█▇▆▁▅▅▄▄▃▃▃▃▃▂▂▃▃▂▂▁▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂▂▂ ▄
  15.7 μs         Histogram: frequency by time         17.7 μs <

 Memory estimate: 7.55 KiB, allocs estimate: 156.

julia> @benchmark GAP.Globals.Orbit(G.X,1)
BenchmarkTools.Trial: 10000 samples with 10 evaluations.
 Range (min … max):  1.608 μs …  5.179 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     1.658 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.675 μs ± 88.837 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

       █▁▆  ▂
  ▁▂▅▅▆███▇▆█▅█▄▄▅▃▄▂▂▃▂▂▂▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▂
  1.61 μs        Histogram: frequency by time        1.95 μs <

 Memory estimate: 624 bytes, allocs estimate: 19.

```
That's an order of magnitude difference in performance and memory usage.

Admittedly some is due to a bad (slow) conversion from GAP integer lists to `Vector{Int}` (which is partially caused by an unnecessary `IdDict` allocation meant for recursive conversions... patch for this will come). We can be "fair" and force the GAP version to go through that, too, but it doesn't matter much.
```
julia> @benchmark Vector{Int}(GAP.Globals.Orbit(G.X,1))
BenchmarkTools.Trial: 10000 samples with 9 evaluations.
 Range (min … max):  2.162 μs …   9.556 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     2.273 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   2.284 μs ± 132.072 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

             ▅  ▇▂ ▁█▁  ▅  ▃
  ▁▁▁▂▂▂▃▇▅▅▆█▇████████▇█▆▆█▆▅▅▆▄▃▂▄▂▂▃▂▁▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▃
  2.16 μs         Histogram: frequency by time        2.51 μs <

 Memory estimate: 1.11 KiB, allocs estimate: 27.
```

It gets worse (relatively) for larger degrees:
```
julia> G = symmetric_group(500)
Sym(500)

julia> @benchmark collect(orbit(G, 1))
BenchmarkTools.Trial: 8759 samples with 1 evaluation.
 Range (min … max):  540.416 μs …  39.392 ms  ┊ GC (min … max): 0.00% … 98.33%
 Time  (median):     552.916 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   569.687 μs ± 495.664 μs  ┊ GC (mean ± σ):  1.65% ±  2.06%

     ▄▆█▇▆▄
  ▁▃▇███████▆▅▄▄▄▄▄▄▄▄▄▃▃▂▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▃
  540 μs           Histogram: frequency by time          631 μs <

 Memory estimate: 141.48 KiB, allocs estimate: 2672.

julia> @benchmark GAP.Globals.Orbit(G.X,1)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  34.333 μs … 84.334 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     36.250 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   36.713 μs ±  2.544 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

    ▇▇▃▅▇█▆▅▅▅▄▂
  ▃██████████████▇▆▅▄▄▃▃▂▂▂▂▂▂▂▂▂▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▃
  34.3 μs         Histogram: frequency by time        46.8 μs <

 Memory estimate: 25.52 KiB, allocs estimate: 34.

julia> @benchmark Vector{Int}(GAP.Globals.Orbit(G.X,1))
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  59.458 μs …  41.642 ms  ┊ GC (min … max): 0.00% … 99.69%
 Time  (median):     62.917 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   69.460 μs ± 416.025 μs  ┊ GC (mean ± σ):  5.98% ±  1.00%

  ▅▇██▇▇▆▅▄▃▃▂▂▁▁▁▁▁▁                                          ▂
  ██████████████████████▇▇▆█▇▇▇▇▆▆▆▆▇▆▅▆▆▅▆▅▃▅▃▅▅▅▄▅▄▃▃▃▁▄▅▁▆▃ █
  59.5 μs       Histogram: log(frequency) by time       114 μs <

 Memory estimate: 37.72 KiB, allocs estimate: 537.

```

I have some branches for improving permutation group performance that I started for the Origami people, and which I should get ready (after the book (TM)), and which should be tested with this; but I suspect a much bigger part of the problem is that we don't let GAP use `OnPoints`, but rather give it a wrapper function which calls Julia's operator `^` which then delegates to ... `OnPoints` (effectively). This is obviously introducing overhead, but more so, it prevents GAP from detecting that it is in this "easy" case.

(Actually, we have a Julia native orbit function which we use in some cases, maybe also this one; but even if my though above is not applicable here, it certainly is in other cases; oh and if we use the native Julia `orbit` function, that's in some sense even worse, it shouldn't be so slow...)

**Comment by mjrodgers** [comment]
I think this can be closed as addressed by #4307 , there can of course always be more improvements down the line but there can be another issue opened if the speed continues to be a problem.

**Comment by fingolfin** [comment]
But has it been addressed? It certainly is better in that it doesn't seem to get slower anymore with larger degrees, but I still see a factor 3 difference:
```
julia> G = symmetric_group(5)
Symmetric group of degree 5

julia> @benchmark collect(orbit(G, 1))
BenchmarkTools.Trial: 10000 samples with 6 evaluations per sample.
 Range (min … max):  5.354 μs …  30.903 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     5.875 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   5.998 μs ± 989.118 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

   ▅█▅▁ ▂▆▄▂▄▂
  ▃████▇███████▆▆▆▄▄▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂▂▂▂▂▂▂▂▂▂▂▂▂ ▃
  5.35 μs         Histogram: frequency by time        9.27 μs <

 Memory estimate: 3.55 KiB, allocs estimate: 81.

julia> @benchmark GAP.Globals.Orbit(G.X,1)
BenchmarkTools.Trial: 10000 samples with 10 evaluations per sample.
 Range (min … max):  1.817 μs …  5.492 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     1.863 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.877 μs ± 74.093 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

          ▂▄▇█ █▆▄▂
  ▂▂▂▃▄▆▁█████▁█████▆▁▅▄▄▄▄▁▄▄▄▄▃▃▁▃▃▃▂▃▁▂▂▂▂▃▂▁▂▂▂▂▂▁▂▂▂▂▂▂ ▃
  1.82 μs        Histogram: frequency by time        2.02 μs <

 Memory estimate: 624 bytes, allocs estimate: 19.
```

and

```
julia> G = symmetric_group(500)
Symmetric group of degree 500

julia> @benchmark collect(orbit(G, 1))
BenchmarkTools.Trial: 10000 samples with 1 evaluation per sample.
 Range (min … max):  106.958 μs … 111.555 ms  ┊ GC (min … max):  0.00% … 99.85%
 Time  (median):     114.542 μs               ┊ GC (median):     0.00%
 Time  (mean ± σ):   148.240 μs ±   1.616 ms  ┊ GC (mean ± σ):  21.18% ±  1.99%

      ▅▁█▇
  ▂▃▂▇█████▅▄▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▂
  107 μs           Histogram: frequency by time          175 μs <

 Memory estimate: 87.56 KiB, allocs estimate: 1600.

julia> @benchmark GAP.Globals.Orbit(G.X,1)
BenchmarkTools.Trial: 10000 samples with 1 evaluation per sample.
 Range (min … max):  33.166 μs … 130.125 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     35.416 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   35.480 μs ±   1.920 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

        ▁ ▁    ▁▁▁▃ ▅▆▅█▄█▂▄▃
  ▂▂▃▅▅██▇█▆▇▇▆██████████████▇█▆▆▆▄▅▄▄▄▃▄▃▃▃▃▂▃▂▂▂▂▂▂▂▂▂▂▁▂▂▂▂ ▄
  33.2 μs         Histogram: frequency by time         39.7 μs <

 Memory estimate: 25.58 KiB, allocs estimate: 34.

```

**Comment by mjrodgers** [comment]
There are updated benchmarks in the conversation on #722
