### ISSUE TITLE
CI: Errors one some RPTU runners

### ISSUE THREAD

**Issue by benlorenz** [oscar-system/Oscar.jl#4404]
While checking various CI logs and doing a bunch of re-runs I have seen two recurring errors on the RPTU runners:
- Broken julia registry installation here https://github.com/oscar-system/Oscar.jl/actions/runs/12331643675/job/34431978695#step:5:52 which causes an installation error for AlgebraicSolving:
  ```
   Run julia-actions/julia-buildpkg@v1
   Run echo "JULIA_PKG_SERVER_REGISTRY_PREFERENCE=${JULIA_PKG_SERVER_REGISTRY_PREFERENCE:-eager}" >> ${GITHUB_ENV}
   Run if "false" == "false" && !isdir(DEPOT_PATH[1])
   registry `General` already exist in `~/oscar-runners/runner-07/julia/registries/General`.
   ERROR: LoadError: Unsatisfiable requirements detected for package AlgebraicSolving [66b61cbe]:
    AlgebraicSolving [66b61cbe] log:
    ├─AlgebraicSolving [66b61cbe] has no known versions!
    └─restricted to versions 0.8 by Oscar [f1435218] — no versions left
      └─Oscar [f1435218] log:
        ├─possible versions are: 1.3.0 or uninstalled
        └─Oscar [f1435218] is fixed to version 1.3.0-DEV
  ```
  This seems to happen only on runner-07. And probably only affects the folder-based registry and not the toml file that is used by newer julia versions (other than 1.6).
- Julia installation error here https://github.com/oscar-system/Oscar.jl/actions/runs/12331643675/job/34431979228#step:3:8:
  ```
  Run julia-actions/setup-julia@v2
  Error: Unable to locate executable file: julia. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
  ```
  This happens (only?) on runner-04 and only for julia 1.11.

Maybe @aaruni96 can have a look locally to clean out the registry folder for runner-07 and have a look at the installation of runner-04 ?

**Comment by aaruni96** [comment]
### Runner 04
For some reason, runner 04 doesn't have the bin folder for jula 1.11.

```bash
 $ find ./ -name "julia" | grep "bin"
./_work/_tool/julia/1.6.7/x64/bin/julia
./_work/_tool/julia/1.10.5/x64/bin/julia
./_work/_tool/julia/1.11-nightly/x64/bin/julia
./_work/_tool/julia/1.10.7/x64/bin/julia
./_work/_tool/julia/nightly/x64/bin/julia
```

Github runner is supposed to manage this entire folder on its own, so I am not sure what to do. Currently, I will rename `_work` to `_work.bak`, and make a new directory `_work`, restart the runner, and hope for the best ?

### Runner 07
For some reason, runner 07 has this extra directory which no other runner has :

```
/home/oscarci-tester/oscar-runners/runner-07/julia/environments/v1.6
```
I will remove this directory , restart the runner, and hope for the best ?

I will try these changes if you think this is heading in a reasonable direction @benlorenz @fingolfin

**Comment by lgoettgens** [comment]
both seem reasonable to me

**Comment by aaruni96** [comment]
I have made these changes. Lets see if these two runners now behave.

**Comment by joschmitt** [comment]
Apparently runner 07 is still unhappy:
```
Run julia-actions/julia-buildpkg@v1
Run echo "JULIA_PKG_SERVER_REGISTRY_PREFERENCE=${JULIA_PKG_SERVER_REGISTRY_PREFERENCE:-eager}" >> ${GITHUB_ENV}
Run if "false" == "false" && !isdir(DEPOT_PATH[1])
registry `General` already exist in `~/oscar-runners/runner-07/julia/registries/General`.
ERROR: LoadError: Unsatisfiable requirements detected for package Nemo [2edaba10]:
 Nemo [2edaba10] log:
 ├─possible versions are: 0.9.0-0.47.5 or uninstalled
 └─restricted to versions 0.48 by Oscar [f1435218] — no versions left
   └─Oscar [f1435218] log:
     ├─possible versions are: 1.3.0 or uninstalled
     └─Oscar [f1435218] is fixed to version 1.3.0-DEV
```
from https://github.com/oscar-system/Oscar.jl/actions/runs/12427974648/job/34698739866?pr=4409 .

**Comment by aaruni96** [comment]
I don't understand this, but once the current job on runner 07 is finished, I will delete the julia depot, and make it start from scratch, which *SHOULD* fix it ?

**Comment by aaruni96** [comment]
Done, runner 07 should behave now ?

**Comment by aaruni96** [comment]
On runner 4 :

```
2024-12-22 15:22:50Z: Job test (1.11, long, Linux) completed with result: Succeeded
```

On runner 7 :

```
2024-12-22 03:37:35Z: Job test (1.6, long, Linux) completed with result: Succeeded
```

So, this should be fixed.

**Comment by benlorenz** [comment]
Thanks!

**Comment by benlorenz** [comment]
The registry issue with 1.6 appeared again, but this time on runner 13:
https://github.com/oscar-system/Oscar.jl/actions/runs/12483496947/job/34839383058#step:5:51
```
registry `General` already exist in `~/oscar-runners/runner-13/julia/registries/General`.
ERROR: LoadError: Unsatisfiable requirements detected for package JSON3 [0f8b85d8]:
 JSON3 [0f8b85d8] log:
 ├─JSON3 [0f8b85d8] has no known versions!
 └─restricted to versions 1.13.2-1 by Oscar [f143[52](https://github.com/oscar-system/Oscar.jl/actions/runs/12483496947/job/34839383058#step:5:55)18] — no versions left
   └─Oscar [f1435218] log:
     ├─possible versions are: 1.3.0 or uninstalled
     └─Oscar [f1435218] is fixed to version 1.3.0-DEV
```

Can you create a tarball from `~/oscar-runners/runner-13/julia/registries` and upload it somewhere? I would like to understand what is wrong with that folder.

**Comment by aaruni96** [comment]
Had a look in there, and it appears that the registry is simply... incomplete ?

Here's what a normal registry looks like :
```
$ ls -lah ~/oscar-runners/runner-07/julia/registries/General
total 1.6M
drwx------   31 oscarci-tester oscarci-tester 4.0K Dec 25 04:15 .
drwxr-xr-x    3 oscarci-tester oscarci-tester 4.0K Dec 25 04:15 ..
drwxr-xr-x  538 oscarci-tester oscarci-tester  20K Dec 25 04:15 A
drwxr-xr-x  489 oscarci-tester oscarci-tester  20K Dec 25 04:15 B
drwxr-xr-x  832 oscarci-tester oscarci-tester  36K Dec 25 04:15 C
drwxr-xr-x    2 oscarci-tester oscarci-tester 4.0K Dec 25 04:15 .ci
-rw-r--r--    1 oscarci-tester oscarci-tester  13K Dec 25 04:15 CONTRIBUTING.md
drwxr-xr-x  561 oscarci-tester oscarci-tester  20K Dec 25 04:15 D
drwxr-xr-x  350 oscarci-tester oscarci-tester  16K Dec 25 04:15 E
drwxr-xr-x  478 oscarci-tester oscarci-tester  20K Dec 25 04:15 F
drwxr-xr-x  498 oscarci-tester oscarci-tester  20K Dec 25 04:15 G
drwxr-xr-x    3 oscarci-tester oscarci-tester 4.0K Dec 25 04:15 .github
-rw-r--r--    1 oscarci-tester oscarci-tester   24 Dec 25 04:15 .gitignore
drwxr-xr-x  235 oscarci-tester oscarci-tester  12K Dec 25 04:15 H
drwxr-xr-x  364 oscarci-tester oscarci-tester  20K Dec 25 04:15 I
drwxr-xr-x  164 oscarci-tester oscarci-tester 4.0K Dec 25 04:15 J
drwxr-xr-x   28 oscarci-tester oscarci-tester 4.0K Dec 25 04:15 jll
drwxr-xr-x  148 oscarci-tester oscarci-tester 4.0K Dec 25 04:15 K
drwxr-xr-x  422 oscarci-tester oscarci-tester  20K Dec 25 04:15 L
-rw-r--r--    1 oscarci-tester oscarci-tester 1.1K Dec 25 04:15 LICENSE.md
drwxr-xr-x  801 oscarci-tester oscarci-tester  36K Dec 25 04:15 M
drwxr-xr-x  315 oscarci-tester oscarci-tester  12K Dec 25 04:15 N
drwxr-xr-x  300 oscarci-tester oscarci-tester  12K Dec 25 04:15 O
drwxr-xr-x  833 oscarci-tester oscarci-tester  36K Dec 25 04:15 P
drwxr-xr-x  196 oscarci-tester oscarci-tester  12K Dec 25 04:15 Q
drwxr-xr-x  465 oscarci-tester oscarci-tester  20K Dec 25 04:15 R
-rw-r--r--    1 oscarci-tester oscarci-tester  25K Dec 25 04:15 README.md
-rw-r--r--    1 oscarci-tester oscarci-tester 1.1M Dec 25 04:15 Registry.toml
drwxr-xr-x 1219 oscarci-tester oscarci-tester  40K Dec 25 04:15 S
drwxr-xr-x  543 oscarci-tester oscarci-tester  20K Dec 25 04:15 T
-rw-r--r--    1 oscarci-tester oscarci-tester   59 Dec 25 04:15 .tree_info.toml
drwxr-xr-x  130 oscarci-tester oscarci-tester 4.0K Dec 25 04:15 U
drwxr-xr-x  134 oscarci-tester oscarci-tester 4.0K Dec 25 04:15 V
drwxr-xr-x  148 oscarci-tester oscarci-tester 4.0K Dec 25 04:15 W
drwxr-xr-x   53 oscarci-tester oscarci-tester 4.0K Dec 25 04:15 X
drwxr-xr-x   42 oscarci-tester oscarci-tester 4.0K Dec 25 04:15 Y
drwxr-xr-x   31 oscarci-tester oscarci-tester 4.0K Dec 25 04:15 Z
```

And here's the problematic registry from runner-13 

```
$ ls -lah General
total 1.3M
drwx------   17 oscarci-tester oscarci-tester 4.0K Dec 24 13:30 .
drwxr-xr-x    3 oscarci-tester oscarci-tester 4.0K Dec 24 13:33 ..
drwxr-xr-x   28 oscarci-tester oscarci-tester 4.0K Dec 24 04:16 jll
drwxr-xr-x  593 oscarci-tester oscarci-tester  36K Dec 24 13:30 M
drwxr-xr-x  315 oscarci-tester oscarci-tester  12K Dec 24 04:16 N
drwxr-xr-x  300 oscarci-tester oscarci-tester  12K Dec 24 04:16 O
drwxr-xr-x  832 oscarci-tester oscarci-tester  36K Dec 24 04:16 P
drwxr-xr-x  196 oscarci-tester oscarci-tester  12K Dec 24 04:16 Q
drwxr-xr-x  465 oscarci-tester oscarci-tester  20K Dec 24 04:16 R
-rw-r--r--    1 oscarci-tester oscarci-tester  25K Dec 24 04:16 README.md
-rw-r--r--    1 oscarci-tester oscarci-tester 1.1M Dec 24 04:16 Registry.toml
drwxr-xr-x 1219 oscarci-tester oscarci-tester  40K Dec 24 04:16 S
drwxr-xr-x  543 oscarci-tester oscarci-tester  20K Dec 24 04:16 T
drwxr-xr-x  130 oscarci-tester oscarci-tester 4.0K Dec 24 04:16 U
drwxr-xr-x  134 oscarci-tester oscarci-tester 4.0K Dec 24 04:16 V
drwxr-xr-x  148 oscarci-tester oscarci-tester 4.0K Dec 24 04:16 W
drwxr-xr-x   53 oscarci-tester oscarci-tester 4.0K Dec 24 04:16 X
drwxr-xr-x   42 oscarci-tester oscarci-tester 4.0K Dec 24 04:16 Y
drwxr-xr-x   31 oscarci-tester oscarci-tester 4.0K Dec 24 04:16 Z
```

Its also only half the size of the "correct" registry: 131M v/s 238M.

**Comment by aaruni96** [comment]
Here's a link to the tarball : https://seafile.rlp.net/f/b2c68cde938e482c8d55/ . The `General.tar.gz` appears to have all the files, maybe the untarring is failing somewhere for some reason ?

**Comment by benlorenz** [comment]
Thanks for the file!

I think some of the registry handling is flawed in 1.6:
If a job is cancelled at the wrong time we end up with an incomplete extraction / or incomplete removal.
Maybe this abort during the registry update caused the incomplete registry:
https://github.com/oscar-system/Oscar.jl/actions/runs/12481706367/job/34834635527?pr=4370#step:5:60

Once there is a folder `General` it is assumed that there is a registry to be used but if it does not contain a `.tree_info.toml` (or `.git`) it will never be updated or checked. And that file is only written after the extraction is complete. Also any update to the registry implies another cycle of removal + extraction + writing the tree-info file that might abort at the wrong time.
Usually this is not a problem in the CI as each job either has no registry or retrieves it from the cache of a successful run (which should have a correct registry).

As a workaround I would suggest either:
1) For the self-hosted runners we add an extra step before build-package that does something like 
   ```
   [ -d registries/General ] && [ ! -f registries/General/.tree_info.toml ] && rm -rf registries/General
   ```
   to remove broken registry folders. The path needs some adjustment but I don't know which environment variable should contain the correct path to the depot.
2) We force all registry instances to git registries, this can be used by all julia versions and should be safer as it does not require unpacking on every update (for 1.6). Note that recent julia versions will print some annoying info that the git registry is slow but that could be suppressed.

**Comment by fingolfin** [comment]
This could also be considered as yet another paper cut encouraging us to drop support for older Julia versions; i.e. not enough on its own as long as we cab reasonably deal with it, but it adds to the bleeding

**Comment by aaruni96** [comment]
I have implemented the first workaround for all the runners. This particular problem with incomplete registries should not occur again.

**Comment by benlorenz** [comment]
I have bad news, this seems to be back as this does look very much like a corrupted registry again: https://github.com/oscar-system/Oscar.jl/actions/runs/12710045922/job/35430340738#step:5:52

```
registry `General` already exist in `~/oscar-runners/runner-02/julia/registries/General`.
ERROR: LoadError: Unsatisfiable requirements detected for package JSON3 [0f8b85d8]:
 JSON3 [0f8b85d8] log:
 ├─JSON3 [0f8b85d8] has no known versions!
 └─restricted to versions 1.13.2-1 by Oscar [f1435218] — no versions left
   └─Oscar [f1435218] log:
     ├─possible versions are: 1.3.0 or uninstalled
     └─Oscar [f1435218] is fixed to version 1.3.0-DEV
```

**Comment by aaruni96** [comment]
This was my mistake: I made the cleanup script, and forgot to mark it as executable. Now this particular problem should be fixed....

**Comment by lgoettgens** [comment]
This issue still seems to exist. I have just encountered it in https://github.com/oscar-system/Oscar.jl/actions/runs/12763262933/job/35573123007?pr=4421#step:5:52 on `RPTU-Linux-02`.
```julia
ERROR: LoadError: Unsatisfiable requirements detected for package JSON3 [0f8b85d8]:
 JSON3 [0f8b85d8] log:
 ├─JSON3 [0f8b85d8] has no known versions!
 └─restricted to versions 1.13.2-1 by Oscar [f143[52](https://github.com/oscar-system/Oscar.jl/actions/runs/12763262933/job/35573123007?pr=4421#step:5:55)18] — no versions left
   └─Oscar [f1435218] log:
     ├─possible versions are: 1.3.0 or uninstalled
     └─Oscar [f1435218] is fixed to version 1.3.0-DEV
```

**Comment by aaruni96** [comment]
I have tweaked some things again, and will restart the runners once they go idle again. Then this should be fixed... ?

**Comment by HereAround** [comment]
Another instance arose today: https://github.com/oscar-system/Oscar.jl/actions/runs/12786726018/job/35644379702?pr=4467

**Comment by aaruni96** [comment]
I haven't spotted the runners in an idle state yet, so my previous tweak isn't active yet (otherwise if I force the restart, all currently running tests will fail).

**Comment by fingolfin** [comment]
@aaruni96 can't we temporarily take half the runners out of the runner pool, then once they are idle them, then reactivate them and do the same for the other half?

Orthogonal to this: do we have a git repository that contains the config files, script etc. used for all this? E.g. in https://github.com/oscar-system/CIDocu or so. That way we'd have more transparency and more eyes could help spot issues.

**Comment by aaruni96** [comment]
> can't we temporarily take half the runners out of the runner pool

I don't know how one would do this. Change the labels? I don't know if changing the label on a runner would affect any job currently running on it?

> do we have a git repository that contains the config files

the CIDocu repository is meant to have it, I will bump it to the top of my todo list.

**Comment by aaruni96** [comment]
I managed to restart all the normal memory runners (01 through 10). I have removed the `high-memory` label from runners 11, 12, and 13, which means they should not accept any more jobs, but currently running jobs have not been cancelled. I will restart these when they go idle, then add them back to the high memory pool, and repeat the exercise with runners 14 and 15.

I have also made a PR on the CIDocu repository which adds the current linux config to the repo : https://github.com/oscar-system/CIDocu/pull/2 .

**Comment by aaruni96** [comment]
I have restarted 11, 12, and 13, and removed 14 and 15 from pool. Will restart 14, and 15 when they go idle and add them back to pool.

Then, finally, this issue should be resolved ?

**Comment by benlorenz** [comment]
> I have also made a PR on the CIDocu repository which adds the current linux config to the repo : [oscar-system/CIDocu#2](https://github.com/oscar-system/CIDocu/pull/2) .

I added a comment there regarding the rm command which probably wont work in the current form.

**Comment by aaruni96** [comment]
I noticed, and am wondering how it ever worked to begin with (I ran this script manually at least once...)

**Comment by benlorenz** [comment]
If you were inside the correct directory (the julia depot), it could have worked (after trying to remove `rm` but not finding this would not be fatal).

**Comment by fingolfin** [comment]
Is there something left to be done, or can this issue be closed now?

**Comment by benlorenz** [comment]
I don't think there is anything left to do, haven't seen these errors in a while.

**Comment by benlorenz** [comment]
Not sure if the script is running correctly, this did happen again a few days ago:
https://github.com/oscar-system/Oscar.jl/actions/runs/14599889592/job/40955177731
(and I manually removed `~/oscar-runners/runner-05/julia/registries/General`)
